### PR TITLE
allow tools to install on dev16

### PR DESCRIPTION
**Pull request by jmarolf**

### CODE REVIEW

**Comment by rainersigwald** [comment]
I did this manually (local copy of the VSIX unzipped, edited, rezipped) and it didn't work, failing with:

```
11/28/2018 1:47:08 PM - Beginning to install extension to Visual Studio Enterprise 2019 Int Preview...
11/28/2018 1:47:10 PM - Install Error : Microsoft.VisualStudio.ExtensionManager.MissingReferencesException: This extension cannot be installed because the following references are missing:
-Microsoft.VisualStudio.Component.CoreEditor (Microsoft.VisualStudio.Component.CoreEditor)
   at Microsoft.VisualStudio.ExtensionManager.EngineUtilities.EnsureNoMissingReferences(IEnumerable`1 missingRefs)
   at Microsoft.VisualStudio.ExtensionManager.PackageInstaller.PrepareEngineInstall(IDependencyGraph dGraph, IDependencyComparisonSeed seed, Component vsCompPkg, Boolean isProductComponent, Int32& totalInstallationSteps)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)
```

**Comment by jmarolf** [comment]
@rainersigwald 	can you try installing the extension from here? \\mlangfs1\public\jmarolf\project-system-tool\Microsoft.VisualStudio.ProjectSystem.Tools.vsix

**Comment by drewnoakes** [comment]
The VSIX installed for me in d16 int preview and d16.0stg. Tested successfully in 28325.102.d16.0stg.

Thanks for fixing this.

**Comment by rainersigwald** [comment]
Installed for me too. Thanks!

**Pull request merged**
