### PR TITLE
Fix build/installation problems

### LINKED ISSUE #36: After installing Extension loading a solution causes error.
image

### PR DESCRIPTION
**Pull request by panopticoncentral**
To unblock installation problems, I removed the dependence on ValueTuple since it wasn't a huge thing. This fixes #36.

I also updated the manifest to target Pro rather than Community since that blocks installs on Pro. #30

### CODE REVIEW

**Comment by natelowry** [comment]
Nice!  Was considering doing this too.  Would changing the target framework to 4.7 and removing the `PackageReference` have worked too?  I tried that, but ran into other dependency issues.  Just curious...

**Comment by saul** [comment]
This still doesn't work for us on VS Pro 15.3.1 - did anyone test this? Looking at other extensions that work on both Pro and Community, they just use `[15.0]` as the target version.

**Comment by panopticoncentral** [comment]
@natelowry I hadn't tried that. I think there are issues with the version of the framework that VS uses? I looked at this a long time ago and I forget.

@saul The APIs that the extension depends on were introduced in 15.4, so this cannot be installed on an earlier build of VS, that's by design, unfortunately.

**Comment by saul** [comment]
That explains it! I was a bit confused by the 15.0.* version number - one day I’ll undersrand VS versioning :)

**Pull request merged**
