### PR TITLE
Log workspace kind and document client name

### PR DESCRIPTION
**Pull request by davidwengier**
FYI @NTaylorMullen and @dibarbet, this should hopefully help tracking down some LSP/Razor issues.

Certainly would be useful in an issue currently being looked at :)

### CODE REVIEW

**Review by NTaylorMullen — APPROVED** [review]

**Comment by dibarbet** [comment]
@davidwengier is this related to https://github.com/dotnet/roslyn/issues/54547#issuecomment-883116301

**Review by dibarbet — APPROVED** [review]

**Comment by davidwengier** [comment]
Not intentionally :)

@NTaylorMullen is investigating an issue that we originally thought could fixed by my project system changes, but the workspace log confirmed that Roslyn knew about the Razor document. The only other explanation I could see for the LSP server not finding it would be if there wasn't a client name associated to it (or the platform has a bug where its not sending the client name properly), but there isn't a way to confirm that. So now there is.

**Comment by dibarbet** [comment]
> The only other explanation I could see for the LSP server not finding it would be if there wasn't a client name associated to it

That also matches the scenario I hit under the debugger on that issue, the document missing the client name service.
Maybe we should consider adding this to the loghub logs on the roslyn side when we lookup the document (aka record how many documents we found before we filtered by client name).

**Comment by davidwengier** [comment]
Taylor is looking at a dump file now and it does seem to be the same, yes. More logs would be good, its only lucky that this was an internal user so we were able to get them to install the extension etc. "Found the document, but not for the client name 'X'" would be very useful info, because we also don't seem to log the client name, so we can't see if its Roslyn or platform that is wrong.

**Review by drewnoakes — APPROVED** [review]

**Comment by davidwengier** [comment]
Thanks Drew!

**Pull request merged**
