### PR TITLE
Move to editor model for viewing binary logs (+ some cleanups)

### PR DESCRIPTION
**Pull request by panopticoncentral**
The current model for viewing binary logs is a single window that contains all of the logs you have open. My idea was that we might want to do analysis across multiple logs. However, that doesn't seem to be taking shape, and it also makes it difficult to add different views of the logs. So this PR moves the model to be editor-based. So when you open up a log, you get a single editor window that now has several views, including summaries of targets, tasks and evaluations done. This seems to be better/more useful.

I also removed some crud from the evaluation model that is actually never set/used. And I tried to make log load a little more resilient to logs that don't look like we expect them to.

### CODE REVIEW

**Comment by jmarolf** [comment]
Looks like we'll need infra changes to build against 4.7.2

**Comment by panopticoncentral** [comment]
@jmarolf Yes, I think that was for other changes I was trying to make, but we don't need to do it at this point.

**Comment by panopticoncentral** [comment]
@jmarolf @drewnoakes @KirillOsenkov Any objections?

**Comment by panopticoncentral** [comment]
@drewnoakes It's the same thing, it represents the evaluation information from the log file.

**Pull request merged**
